<script lang="ts">
  import Row from "./components/Row.svelte";
  import ParamsForm from "./components/ParamsForm.svelte";
  export let appTitle: string = "Hold My Pics";
  export let imageCount: number = 0;

  let imgCountStr = imageCount.toLocaleString(undefined, {
    style: "decimal",
    maximumFractionDigits: 0,
  });
</script>

<style>
  :global(body) {
    font-family: "Fira Sans";
  }
  :global(header, footer, h1, h2, h3, h4, h5, h6) {
    font-family: "Spectral";
  }
  .App {
    text-align: center;
  }
</style>

<div class="App">
  <Row>
    <h1>{appTitle}</h1>
  </Row>
  <Row>
    <p>
      Ever needed to create some placeholder images? Here's an easy was to do
      that.
    </p>
  </Row>
  <Row>
    <h2>~{imgCountStr} Images Generated</h2>
  </Row>
  <Row>
    <img
      src="https://holdmypics.com/api/638x328/cef/555/png/?text=Something+Funny&font=overpass"
      alt="Generated by this site" />
  </Row>
  <Row>
    <code>Endpoint</code>
  </Row>

  <ParamsForm />
</div>
