<script lang="ts">
  import type { ImageFormProps, Option, UpdateEvent } from "../typing";
  import { onlyTruthy } from "../helpers";

  import Row from "../helpers/Row.svelte";
  import HelpText from "./HelpText.svelte";
  import CustomSelect from "./CustomSelect.svelte";
  import ColorInput from "./ColorInput.svelte";
  import CopyButton from "./CopyButton.svelte";
  import { ALL_FONTS, ALL_FORMATS } from "../helpers/consts";

  export let props: ImageFormProps;
  export let host: string = "https://holdmypics.com";

  let font: string = "overpass";
  let randomText: boolean = false;

  let form: HTMLFormElement;
  let textInput: HTMLInputElement | undefined;

  const updateFg = ({ detail }: UpdateEvent) => (props.fg = detail.value);
  const updateBg = ({ detail }: UpdateEvent) => (props.bg = detail.value);

  const randomChanged = () => textInput && (textInput.disabled = randomText);

  let textParam: string | undefined;
  $: textParam = textInput?.disabled
    ? undefined
    : props.text?.length ?? 0 > 0
    ? props.text
    : undefined;

  let params: string;
  $: params = new URLSearchParams(
    onlyTruthy([
      ["font", font || undefined],
      ["text", textParam],
      ["random_text", randomText ? "" : undefined],
    ])
  ).toString();

  // let size: string;
  // $: size = `${props.width}x${props.height}`;
  let url: string;
  $: url = [
    "/api",
    `${props.width}x${props.height}`,
    //size,
    props.bg,
    props.fg,
    props.fmt,
    `${params.length ? "?" : ""}${params}`,
  ].join("/");

  const fontOptions: Option[] = [""].concat(ALL_FONTS).map((font) => ({
    label: font,
    value: font.toLowerCase().replace(/\s/, "-"),
    selected: /overpass/i.test(font),
  }));
  const fmtOptions: Option[] = ALL_FORMATS.map((fmt) => ({
    label: fmt,
    value: fmt,
    selected: fmt === "png",
  }));
</script>

<style>
  .ImageForm {
    @apply w-full py-4 max-w-xl mx-auto mb-4 bg-white px-4;
    @apply text-gray-900;
    @apply border border-indigo-400 rounded;
  }
  .Image {
    @apply pt-4;
  }
  .form-group {
    @apply w-full;
    @apply flex flex-row justify-between content-start;
    @apply items-baseline;
  }
  .form-group + .form-group {
    @apply mt-3;
  }
  .form-group > * {
    flex: 0 0 50%;
    @apply block;
  }
  .input-group {
    @apply items-center;
  }
  input {
    @apply w-full;
    @apply border-2 border-gray-200 rounded;
    @apply py-1 px-2;
    @apply text-gray-700;
    @apply leading-tight;
  }
  :global(input:not([type="checkbox"])) {
    @apply appearance-none;
    @apply shadow-sm;
  }
  :global(input:focus) {
    @apply outline-none bg-white border-indigo-500;
  }
  :global(input:invalid) {
    @apply border-red-500;
  }
</style>

<div class="Image">
  <Row center={true}>
    {#if import.meta.env.MODE === 'development'}
      <img
        src="https://holdmypics.com/api/638x328/cef/555/png/?text=Something+Funny&font=overpass"
        alt="Generated by this site"
        data-cy="generated-image" />
    {:else}
      <img
        src="{host}{url}"
        alt="Generated by this site"
        data-cy="generated-image" />
    {/if}
  </Row>

  <Row center={true}>
    <code
      class="overflow-hidden hover:underline cursor-pointer"
      data-cy="generated-url">{url}</code>
  </Row>

  <Row center={true}>
    <CopyButton data="{host}{url}" />
  </Row>
</div>

<form bind:this={form} class="ImageForm">
  <div class="form-group">
    <label for="width">Width</label>
    <input
      type="number"
      id="width"
      name="width"
      data-cy="width"
      step="1"
      min="1"
      bind:value={props.width} />
  </div>
  <div class="form-group">
    <label for="height">Height</label>
    <input
      type="number"
      id="height"
      name="height"
      step="1"
      min="1"
      bind:value={props.height} />
  </div>
  <div class="form-group">
    <ColorInput
      label="Foreground Color"
      id="fg"
      value={props.fg}
      on:update={updateFg} />
  </div>
  <div class="form-group">
    <ColorInput
      label="Background Color"
      id="bg"
      value={props.bg}
      on:update={updateBg} />
  </div>

  <div class="form-group">
    <label for="fmt">Format</label>
    <div class="input-group">
      <CustomSelect id="fmt" options={fmtOptions} bind:value={props.fmt} />
      <HelpText><q>jpg</q> and <q>jpeg</q> are equivalent.</HelpText>
    </div>
  </div>

  <div class="form-group">
    <label for="font">Font</label>
    <div class="input-group">
      <CustomSelect id="font" options={fontOptions} bind:value={font} />
      <HelpText>The font of the text.</HelpText>
    </div>
  </div>

  <div id="text-row" class="form-group">
    <label for="text">Text</label>
    <input
      class="pr-0 mr-0 flex-grow"
      type="text"
      id="text"
      name="text"
      bind:this={textInput}
      bind:value={props.text}
      spellcheck={false} />
  </div>
  <div class="form-group" id="random-text-row">
    <label for="randomText">Random Text</label>
    <div class="text-left">
      <input
        class="ml-0"
        name="randomText"
        id="randomText"
        type="checkbox"
        bind:checked={randomText}
        on:change={randomChanged} />
      <HelpText>&nbsp;</HelpText>
    </div>
  </div>
</form>
