<script lang="ts">
  import Row from "./Row.svelte";

  let width: number = 638;
  let height: number = 388;
</script>

<style>
  .ImageForm {
    @apply w-full;
    @apply px-2;
  }
  .form-group {
    @apply pb-4;
    @apply px-10;
    @apply w-full;
    @apply flex;
    @apply flex-row;
    @apply justify-between;
    @apply content-start;
  }
  input {
    @apply shadow;
    @apply border;
    @apply rounded;
    @apply py-1;
    @apply px-2;
    @apply appearance-none;
    @apply text-gray-700;
    @apply leading-tight;
  }
</style>

<Row>
  <img
    src="https://holdmypics.com/api/638x328/cef/555/png/?text=Something+Funny&font=overpass"
    alt="Generated by this site" />
</Row>

<Row>
  <code>/api/{width}x{height}/</code>
</Row>

<form class="ImageForm">
  <div class="form-group">
    <label for="width">Width</label>
    <input type="number" id="width" name="width" bind:value={width} />
  </div>
  <div class="form-group">
    <label for="height">Height</label>
    <input type="number" id="height" name="height" bind:value={height} />
  </div>
  <div class="form-group">
    <label for="fg">Foreground Color</label>
    <input type="text" id="fg" name="fg" />
  </div>
  <div class="form-group">
    <label for="bg">Background Color</label>
    <input type="text" id="bg" name="bg" />
  </div>
</form>
